services:  
  zookeeper:
    image: zookeeper:3.7
    hostname: zookeeper
    ports:
      - '2181:2181'

  clickhouse1:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse1
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_HOST=clickhouse1:9000
    volumes:
      - ./config/clickhouse1/config.d/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse1/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./volume/clickhouse1/data:/var/lib/clickhouse/data
      - ./volume/clickhouse1/logs:/var/log/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    depends_on:
      - zookeeper

  clickhouse2:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse2
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_HOST=clickhouse1:9000
    volumes:
      - ./config/clickhouse2/config.d/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse2/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./volume/clickhouse2/data:/var/lib/clickhouse/data
      - ./volume/clickhouse2/logs:/var/log/clickhouse-server
    ports:
      - '8124:8123'
      - '9001:9000'
    depends_on:
      - zookeeper

volumes:
  clickhouse1_data:
  clickhouse2_data: