global:
  scrape_interval: 5s
  evaluation_interval: 5s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: "kloudmate"
    static_configs:
      - targets:
          - "host.docker.internal:8080"