receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      system:
      memory:
      
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resourcedetection:
    detectors: [env, system, docker]
    timeout: 15s
    override: false

  resource:
    attributes:
      - key: service.name
        action: insert
        from_attribute: host.name
      - key: service.workspace
        action: insert
        value: dev

  batch:
    timeout: 30s
    send_batch_size: 1000

exporters:
  debug:
    verbosity: detailed
  clickhouse:
    endpoint: tcp://host.docker.internal:9000?dial_timeout=10s&compress=lz4&async_insert=1
    create_schema: true
    username: default
    password: default
    timeout: 5s
    database: default
    sending_queue:
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  prometheus:
    endpoint: "0.0.0.0:8889" 

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [resourcedetection, resource, batch]
      exporters: [clickhouse, prometheus]
