receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      system:

processors:
  resourcedetection:
    detectors: [env, system, docker]
    timeout: 2s
    override: false
  resource:
    attributes:
      - key: service.name
        action: insert
        from_attribute: host.name

  batch:
    timeout: 10s
    send_batch_size: 1000

exporters:
  otlphttp:
    endpoint: <>
    headers:
      Authorization: <>


service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, resource, batch]
      exporters: [otlphttp]
