global:
  scrape_interval: 5s
  evaluation_interval: 5s 

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: "otel"
    static_configs:
      - targets:
          - "otel-collector:8889"