services:
  redis-6379:
    image: redis:7.2
    container_name: redis-6379
    ports:
      - "6379:6379"
    volumes:
      - ./redis-6379:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --dir /data
    networks:
      - redis-cluster

  redis-6380:
    image: redis:7.2
    container_name: redis-6380
    ports:
      - "6380:6379"
    volumes:
      - ./redis-6380:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --dir /data
    networks:
      - redis-cluster

  redis-6381:
    image: redis:7.2
    container_name: redis-6381
    ports:
      - "6381:6379"
    volumes:
      - ./redis-6381:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --dir /data
    networks:
      - redis-cluster

  redis-6382:
    image: redis:7.2
    container_name: redis-6382
    ports:
      - "6382:6379"
    volumes:
      - ./redis-6382:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --dir /data
    networks:
      - redis-cluster

  redis-6383:
    image: redis:7.2
    container_name: redis-6383
    ports:
      - "6383:6379"
    volumes:
      - ./redis-6383:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --dir /data
    networks:
      - redis-cluster

  redis-6384:
    image: redis:7.2
    container_name: redis-6384
    ports:
      - "6384:6379"
    volumes:
      - ./redis-6384:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --dir /data
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge